exclude: |
  (?x)(
    (^vendor/)|
    (.deepcopy.go$)
  )
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
    exclude: ui/web/external/.*
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: pretty-format-json
    args:
    - --autofix
  - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
  - id: go-fmt

- repo: local
  hooks:
  - id: goimports
    name: goimports
    entry: .deps/bin/goimports -local github.com/thetechnick/linuxcnc-ui -w -l
    exclude: ".*(.pb.go|.pb.gw.go)"
    language: system
    types: [go]

  - id: golangci-lint
    name: golangci-lint
    entry: .deps/bin/golangci-lint run
    language: script
    pass_filenames: false
    types: [go]

  - id: go-mod-tidy
    name: go-mod-tidy
    entry: go mod tidy
    language: system
    exclude: ".*"
    pass_filenames: false
    always_run: true

  - id: generate
    name: generate
    entry: go run ./cmd/mage generate
    language: system
    exclude: ".*"
    pass_filenames: false
    always_run: true
