// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: interpreter.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InterpreterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *InterpreterRequest) Reset() {
	*x = InterpreterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterpreterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterpreterRequest) ProtoMessage() {}

func (x *InterpreterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterpreterRequest.ProtoReflect.Descriptor instead.
func (*InterpreterRequest) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{0}
}

func (x *InterpreterRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type InterpreterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instructions []*anypb.Any `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
}

func (x *InterpreterResponse) Reset() {
	*x = InterpreterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterpreterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterpreterResponse) ProtoMessage() {}

func (x *InterpreterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterpreterResponse.ProtoReflect.Descriptor instead.
func (*InterpreterResponse) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{1}
}

func (x *InterpreterResponse) GetInstructions() []*anypb.Any {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type InterpreterPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	A float64 `protobuf:"fixed64,4,opt,name=a,proto3" json:"a,omitempty"`
	B float64 `protobuf:"fixed64,5,opt,name=b,proto3" json:"b,omitempty"`
	C float64 `protobuf:"fixed64,6,opt,name=c,proto3" json:"c,omitempty"`
	U float64 `protobuf:"fixed64,7,opt,name=u,proto3" json:"u,omitempty"`
	V float64 `protobuf:"fixed64,8,opt,name=v,proto3" json:"v,omitempty"`
	W float64 `protobuf:"fixed64,9,opt,name=w,proto3" json:"w,omitempty"`
}

func (x *InterpreterPosition) Reset() {
	*x = InterpreterPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterpreterPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterpreterPosition) ProtoMessage() {}

func (x *InterpreterPosition) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterpreterPosition.ProtoReflect.Descriptor instead.
func (*InterpreterPosition) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{2}
}

func (x *InterpreterPosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *InterpreterPosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *InterpreterPosition) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *InterpreterPosition) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *InterpreterPosition) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *InterpreterPosition) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *InterpreterPosition) GetU() float64 {
	if x != nil {
		return x.U
	}
	return 0
}

func (x *InterpreterPosition) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *InterpreterPosition) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

type CommentInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CommentInstruction) Reset() {
	*x = CommentInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInstruction) ProtoMessage() {}

func (x *CommentInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInstruction.ProtoReflect.Descriptor instead.
func (*CommentInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{3}
}

func (x *CommentInstruction) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type MessageInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageInstruction) Reset() {
	*x = MessageInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInstruction) ProtoMessage() {}

func (x *MessageInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInstruction.ProtoReflect.Descriptor instead.
func (*MessageInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{4}
}

func (x *MessageInstruction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChangeToolInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolNumber int32 `protobuf:"varint,1,opt,name=toolNumber,proto3" json:"toolNumber,omitempty"`
}

func (x *ChangeToolInstruction) Reset() {
	*x = ChangeToolInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeToolInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeToolInstruction) ProtoMessage() {}

func (x *ChangeToolInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeToolInstruction.ProtoReflect.Descriptor instead.
func (*ChangeToolInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeToolInstruction) GetToolNumber() int32 {
	if x != nil {
		return x.ToolNumber
	}
	return 0
}

type UseLengthUnitInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit string `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *UseLengthUnitInstruction) Reset() {
	*x = UseLengthUnitInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseLengthUnitInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseLengthUnitInstruction) ProtoMessage() {}

func (x *UseLengthUnitInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseLengthUnitInstruction.ProtoReflect.Descriptor instead.
func (*UseLengthUnitInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{6}
}

func (x *UseLengthUnitInstruction) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type UseToolLengthOffsetInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *InterpreterPosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *UseToolLengthOffsetInstruction) Reset() {
	*x = UseToolLengthOffsetInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseToolLengthOffsetInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseToolLengthOffsetInstruction) ProtoMessage() {}

func (x *UseToolLengthOffsetInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseToolLengthOffsetInstruction.ProtoReflect.Descriptor instead.
func (*UseToolLengthOffsetInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{7}
}

func (x *UseToolLengthOffsetInstruction) GetPosition() *InterpreterPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type SelectPlaneInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plane string `protobuf:"bytes,1,opt,name=plane,proto3" json:"plane,omitempty"`
}

func (x *SelectPlaneInstruction) Reset() {
	*x = SelectPlaneInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectPlaneInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectPlaneInstruction) ProtoMessage() {}

func (x *SelectPlaneInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectPlaneInstruction.ProtoReflect.Descriptor instead.
func (*SelectPlaneInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{8}
}

func (x *SelectPlaneInstruction) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

type SetXYRotationInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position float64 `protobuf:"fixed64,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *SetXYRotationInstruction) Reset() {
	*x = SetXYRotationInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetXYRotationInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetXYRotationInstruction) ProtoMessage() {}

func (x *SetXYRotationInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetXYRotationInstruction.ProtoReflect.Descriptor instead.
func (*SetXYRotationInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{9}
}

func (x *SetXYRotationInstruction) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type SetG5XOffsetInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Position *InterpreterPosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *SetG5XOffsetInstruction) Reset() {
	*x = SetG5XOffsetInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetG5XOffsetInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetG5XOffsetInstruction) ProtoMessage() {}

func (x *SetG5XOffsetInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetG5XOffsetInstruction.ProtoReflect.Descriptor instead.
func (*SetG5XOffsetInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{10}
}

func (x *SetG5XOffsetInstruction) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SetG5XOffsetInstruction) GetPosition() *InterpreterPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type Set92OffsetInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *InterpreterPosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Set92OffsetInstruction) Reset() {
	*x = Set92OffsetInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set92OffsetInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set92OffsetInstruction) ProtoMessage() {}

func (x *Set92OffsetInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set92OffsetInstruction.ProtoReflect.Descriptor instead.
func (*Set92OffsetInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{11}
}

func (x *Set92OffsetInstruction) GetPosition() *InterpreterPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type SetTraverseRateInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate float64 `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *SetTraverseRateInstruction) Reset() {
	*x = SetTraverseRateInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTraverseRateInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTraverseRateInstruction) ProtoMessage() {}

func (x *SetTraverseRateInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTraverseRateInstruction.ProtoReflect.Descriptor instead.
func (*SetTraverseRateInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{12}
}

func (x *SetTraverseRateInstruction) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type SetFeedModeInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpindleNumber int32 `protobuf:"varint,1,opt,name=spindleNumber,proto3" json:"spindleNumber,omitempty"`
	Mode          int32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *SetFeedModeInstruction) Reset() {
	*x = SetFeedModeInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFeedModeInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFeedModeInstruction) ProtoMessage() {}

func (x *SetFeedModeInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFeedModeInstruction.ProtoReflect.Descriptor instead.
func (*SetFeedModeInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{13}
}

func (x *SetFeedModeInstruction) GetSpindleNumber() int32 {
	if x != nil {
		return x.SpindleNumber
	}
	return 0
}

func (x *SetFeedModeInstruction) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type SetFeedRateInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate float64 `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *SetFeedRateInstruction) Reset() {
	*x = SetFeedRateInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFeedRateInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFeedRateInstruction) ProtoMessage() {}

func (x *SetFeedRateInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFeedRateInstruction.ProtoReflect.Descriptor instead.
func (*SetFeedRateInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{14}
}

func (x *SetFeedRateInstruction) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type StraightTraverseInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineNumber int32                `protobuf:"varint,1,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	Position   *InterpreterPosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *StraightTraverseInstruction) Reset() {
	*x = StraightTraverseInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StraightTraverseInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StraightTraverseInstruction) ProtoMessage() {}

func (x *StraightTraverseInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StraightTraverseInstruction.ProtoReflect.Descriptor instead.
func (*StraightTraverseInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{15}
}

func (x *StraightTraverseInstruction) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *StraightTraverseInstruction) GetPosition() *InterpreterPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type ArcMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstEnd     float64 `protobuf:"fixed64,1,opt,name=firstEnd,proto3" json:"firstEnd,omitempty"`
	SecondEnd    float64 `protobuf:"fixed64,2,opt,name=secondEnd,proto3" json:"secondEnd,omitempty"`
	Rotation     int32   `protobuf:"varint,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	A            float64 `protobuf:"fixed64,4,opt,name=A,proto3" json:"A,omitempty"`
	B            float64 `protobuf:"fixed64,5,opt,name=B,proto3" json:"B,omitempty"`
	C            float64 `protobuf:"fixed64,6,opt,name=C,proto3" json:"C,omitempty"`
	U            float64 `protobuf:"fixed64,7,opt,name=U,proto3" json:"U,omitempty"`
	V            float64 `protobuf:"fixed64,8,opt,name=V,proto3" json:"V,omitempty"`
	W            float64 `protobuf:"fixed64,9,opt,name=W,proto3" json:"W,omitempty"`
	FirstAxis    float64 `protobuf:"fixed64,10,opt,name=firstAxis,proto3" json:"firstAxis,omitempty"`
	SecondAxis   float64 `protobuf:"fixed64,11,opt,name=secondAxis,proto3" json:"secondAxis,omitempty"`
	AxisEndPoint float64 `protobuf:"fixed64,12,opt,name=axisEndPoint,proto3" json:"axisEndPoint,omitempty"`
}

func (x *ArcMove) Reset() {
	*x = ArcMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArcMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArcMove) ProtoMessage() {}

func (x *ArcMove) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArcMove.ProtoReflect.Descriptor instead.
func (*ArcMove) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{16}
}

func (x *ArcMove) GetFirstEnd() float64 {
	if x != nil {
		return x.FirstEnd
	}
	return 0
}

func (x *ArcMove) GetSecondEnd() float64 {
	if x != nil {
		return x.SecondEnd
	}
	return 0
}

func (x *ArcMove) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *ArcMove) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *ArcMove) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ArcMove) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *ArcMove) GetU() float64 {
	if x != nil {
		return x.U
	}
	return 0
}

func (x *ArcMove) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *ArcMove) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *ArcMove) GetFirstAxis() float64 {
	if x != nil {
		return x.FirstAxis
	}
	return 0
}

func (x *ArcMove) GetSecondAxis() float64 {
	if x != nil {
		return x.SecondAxis
	}
	return 0
}

func (x *ArcMove) GetAxisEndPoint() float64 {
	if x != nil {
		return x.AxisEndPoint
	}
	return 0
}

type ArcFeedInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArcMove *ArcMove `protobuf:"bytes,1,opt,name=arcMove,proto3" json:"arcMove,omitempty"`
}

func (x *ArcFeedInstruction) Reset() {
	*x = ArcFeedInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArcFeedInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArcFeedInstruction) ProtoMessage() {}

func (x *ArcFeedInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArcFeedInstruction.ProtoReflect.Descriptor instead.
func (*ArcFeedInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{17}
}

func (x *ArcFeedInstruction) GetArcMove() *ArcMove {
	if x != nil {
		return x.ArcMove
	}
	return nil
}

type StraightFeedInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineNumber int32                `protobuf:"varint,1,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	Position   *InterpreterPosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *StraightFeedInstruction) Reset() {
	*x = StraightFeedInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StraightFeedInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StraightFeedInstruction) ProtoMessage() {}

func (x *StraightFeedInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StraightFeedInstruction.ProtoReflect.Descriptor instead.
func (*StraightFeedInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{18}
}

func (x *StraightFeedInstruction) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *StraightFeedInstruction) GetPosition() *InterpreterPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type StraightProbeInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineNumber int32                `protobuf:"varint,1,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	Position   *InterpreterPosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *StraightProbeInstruction) Reset() {
	*x = StraightProbeInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StraightProbeInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StraightProbeInstruction) ProtoMessage() {}

func (x *StraightProbeInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StraightProbeInstruction.ProtoReflect.Descriptor instead.
func (*StraightProbeInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{19}
}

func (x *StraightProbeInstruction) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *StraightProbeInstruction) GetPosition() *InterpreterPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type RigidTapInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X          float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y          float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z          float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	Scale      float64 `protobuf:"fixed64,4,opt,name=scale,proto3" json:"scale,omitempty"`
	LineNumber int32   `protobuf:"varint,5,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
}

func (x *RigidTapInstruction) Reset() {
	*x = RigidTapInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RigidTapInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RigidTapInstruction) ProtoMessage() {}

func (x *RigidTapInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RigidTapInstruction.ProtoReflect.Descriptor instead.
func (*RigidTapInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{20}
}

func (x *RigidTapInstruction) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RigidTapInstruction) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RigidTapInstruction) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *RigidTapInstruction) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *RigidTapInstruction) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type DwellInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *durationpb.Duration `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *DwellInstruction) Reset() {
	*x = DwellInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interpreter_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DwellInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DwellInstruction) ProtoMessage() {}

func (x *DwellInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DwellInstruction.ProtoReflect.Descriptor instead.
func (*DwellInstruction) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_rawDescGZIP(), []int{21}
}

func (x *DwellInstruction) GetTime() *durationpb.Duration {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_interpreter_proto protoreflect.FileDescriptor

var file_interpreter_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e, 0x63, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a,
	0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x13, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x75, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x76,
	0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x77, 0x22, 0x2e,
	0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2e,
	0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37,
	0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x6f,
	0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x62, 0x0a, 0x1e, 0x55, 0x73, 0x65, 0x54, 0x6f,
	0x6f, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x49, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69,
	0x6e, 0x75, 0x78, 0x63, 0x6e, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x16, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x22, 0x36, 0x0a, 0x18, 0x53,
	0x65, 0x74, 0x58, 0x59, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x71, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x47, 0x35, 0x58, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e,
	0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x65, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x39, 0x32, 0x4f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e, 0x63, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x22, 0x52, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x4d,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x0d, 0x73, 0x70, 0x69, 0x6e, 0x64, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x70, 0x69, 0x6e, 0x64, 0x6c, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x46,
	0x65, 0x65, 0x64, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x7f, 0x0a, 0x1b, 0x53, 0x74, 0x72, 0x61, 0x69, 0x67,
	0x68, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x72, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63,
	0x6e, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x65, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x95, 0x02, 0x0a, 0x07, 0x41, 0x72, 0x63, 0x4d,
	0x6f, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x45, 0x6e, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x42, 0x12, 0x0c, 0x0a, 0x01, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x43, 0x12, 0x0c, 0x0a, 0x01, 0x55, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x55, 0x12, 0x0c, 0x0a, 0x01, 0x56, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x56, 0x12,
	0x0c, 0x0a, 0x01, 0x57, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x57, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x78, 0x69, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x78, 0x69, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x78, 0x69, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x78, 0x69, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x78, 0x69, 0x73, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0c, 0x61, 0x78, 0x69, 0x73, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22,
	0x48, 0x0a, 0x12, 0x41, 0x72, 0x63, 0x46, 0x65, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x72, 0x63, 0x4d, 0x6f, 0x76, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e,
	0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x63, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x07, 0x61, 0x72, 0x63, 0x4d, 0x6f, 0x76, 0x65, 0x22, 0x7b, 0x0a, 0x17, 0x53, 0x74, 0x72,
	0x61, 0x69, 0x67, 0x68, 0x74, 0x46, 0x65, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e,
	0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x65, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7c, 0x0a, 0x18, 0x53, 0x74, 0x72, 0x61, 0x69, 0x67,
	0x68, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e, 0x63, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x13, 0x52, 0x69, 0x67, 0x69, 0x64, 0x54, 0x61, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x10, 0x44,
	0x77, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x82,
	0x01, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x65, 0x74, 0x12, 0x23, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e, 0x63, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63,
	0x6e, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65,
	0x74, 0x65, 0x72, 0x42, 0x23, 0x5a, 0x21, 0x74, 0x68, 0x65, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x63, 0x6b, 0x2e, 0x6e, 0x69, 0x6e, 0x6a, 0x61, 0x2f, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x63, 0x6e,
	0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interpreter_proto_rawDescOnce sync.Once
	file_interpreter_proto_rawDescData = file_interpreter_proto_rawDesc
)

func file_interpreter_proto_rawDescGZIP() []byte {
	file_interpreter_proto_rawDescOnce.Do(func() {
		file_interpreter_proto_rawDescData = protoimpl.X.CompressGZIP(file_interpreter_proto_rawDescData)
	})
	return file_interpreter_proto_rawDescData
}

var file_interpreter_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_interpreter_proto_goTypes = []interface{}{
	(*InterpreterRequest)(nil),             // 0: linuxcnc.api.v1.InterpreterRequest
	(*InterpreterResponse)(nil),            // 1: linuxcnc.api.v1.InterpreterResponse
	(*InterpreterPosition)(nil),            // 2: linuxcnc.api.v1.InterpreterPosition
	(*CommentInstruction)(nil),             // 3: linuxcnc.api.v1.CommentInstruction
	(*MessageInstruction)(nil),             // 4: linuxcnc.api.v1.MessageInstruction
	(*ChangeToolInstruction)(nil),          // 5: linuxcnc.api.v1.ChangeToolInstruction
	(*UseLengthUnitInstruction)(nil),       // 6: linuxcnc.api.v1.UseLengthUnitInstruction
	(*UseToolLengthOffsetInstruction)(nil), // 7: linuxcnc.api.v1.UseToolLengthOffsetInstruction
	(*SelectPlaneInstruction)(nil),         // 8: linuxcnc.api.v1.SelectPlaneInstruction
	(*SetXYRotationInstruction)(nil),       // 9: linuxcnc.api.v1.SetXYRotationInstruction
	(*SetG5XOffsetInstruction)(nil),        // 10: linuxcnc.api.v1.SetG5XOffsetInstruction
	(*Set92OffsetInstruction)(nil),         // 11: linuxcnc.api.v1.Set92OffsetInstruction
	(*SetTraverseRateInstruction)(nil),     // 12: linuxcnc.api.v1.SetTraverseRateInstruction
	(*SetFeedModeInstruction)(nil),         // 13: linuxcnc.api.v1.SetFeedModeInstruction
	(*SetFeedRateInstruction)(nil),         // 14: linuxcnc.api.v1.SetFeedRateInstruction
	(*StraightTraverseInstruction)(nil),    // 15: linuxcnc.api.v1.StraightTraverseInstruction
	(*ArcMove)(nil),                        // 16: linuxcnc.api.v1.ArcMove
	(*ArcFeedInstruction)(nil),             // 17: linuxcnc.api.v1.ArcFeedInstruction
	(*StraightFeedInstruction)(nil),        // 18: linuxcnc.api.v1.StraightFeedInstruction
	(*StraightProbeInstruction)(nil),       // 19: linuxcnc.api.v1.StraightProbeInstruction
	(*RigidTapInstruction)(nil),            // 20: linuxcnc.api.v1.RigidTapInstruction
	(*DwellInstruction)(nil),               // 21: linuxcnc.api.v1.DwellInstruction
	(*anypb.Any)(nil),                      // 22: google.protobuf.Any
	(*durationpb.Duration)(nil),            // 23: google.protobuf.Duration
}
var file_interpreter_proto_depIdxs = []int32{
	22, // 0: linuxcnc.api.v1.InterpreterResponse.instructions:type_name -> google.protobuf.Any
	2,  // 1: linuxcnc.api.v1.UseToolLengthOffsetInstruction.position:type_name -> linuxcnc.api.v1.InterpreterPosition
	2,  // 2: linuxcnc.api.v1.SetG5XOffsetInstruction.position:type_name -> linuxcnc.api.v1.InterpreterPosition
	2,  // 3: linuxcnc.api.v1.Set92OffsetInstruction.position:type_name -> linuxcnc.api.v1.InterpreterPosition
	2,  // 4: linuxcnc.api.v1.StraightTraverseInstruction.position:type_name -> linuxcnc.api.v1.InterpreterPosition
	16, // 5: linuxcnc.api.v1.ArcFeedInstruction.arcMove:type_name -> linuxcnc.api.v1.ArcMove
	2,  // 6: linuxcnc.api.v1.StraightFeedInstruction.position:type_name -> linuxcnc.api.v1.InterpreterPosition
	2,  // 7: linuxcnc.api.v1.StraightProbeInstruction.position:type_name -> linuxcnc.api.v1.InterpreterPosition
	23, // 8: linuxcnc.api.v1.DwellInstruction.time:type_name -> google.protobuf.Duration
	0,  // 9: linuxcnc.api.v1.InterpreterService.Interpret:input_type -> linuxcnc.api.v1.InterpreterRequest
	1,  // 10: linuxcnc.api.v1.InterpreterService.Interpret:output_type -> linuxcnc.api.v1.InterpreterResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_interpreter_proto_init() }
func file_interpreter_proto_init() {
	if File_interpreter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interpreter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterpreterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterpreterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterpreterPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeToolInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseLengthUnitInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseToolLengthOffsetInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectPlaneInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetXYRotationInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetG5XOffsetInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set92OffsetInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTraverseRateInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFeedModeInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFeedRateInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StraightTraverseInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArcMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArcFeedInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StraightFeedInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StraightProbeInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RigidTapInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interpreter_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DwellInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interpreter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interpreter_proto_goTypes,
		DependencyIndexes: file_interpreter_proto_depIdxs,
		MessageInfos:      file_interpreter_proto_msgTypes,
	}.Build()
	File_interpreter_proto = out.File
	file_interpreter_proto_rawDesc = nil
	file_interpreter_proto_goTypes = nil
	file_interpreter_proto_depIdxs = nil
}
