// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StatusServiceClient is the client API for StatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusServiceClient interface {
	Get(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetResponse, error)
	Watch(ctx context.Context, in *StatusWatchRequest, opts ...grpc.CallOption) (StatusService_WatchClient, error)
}

type statusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusServiceClient(cc grpc.ClientConnInterface) StatusServiceClient {
	return &statusServiceClient{cc}
}

func (c *statusServiceClient) Get(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetResponse, error) {
	out := new(StatusGetResponse)
	err := c.cc.Invoke(ctx, "/linuxcnc.api.v1.StatusService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusServiceClient) Watch(ctx context.Context, in *StatusWatchRequest, opts ...grpc.CallOption) (StatusService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StatusService_serviceDesc.Streams[0], "/linuxcnc.api.v1.StatusService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &statusServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StatusService_WatchClient interface {
	Recv() (*StatusWatchResponse, error)
	grpc.ClientStream
}

type statusServiceWatchClient struct {
	grpc.ClientStream
}

func (x *statusServiceWatchClient) Recv() (*StatusWatchResponse, error) {
	m := new(StatusWatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StatusServiceServer is the server API for StatusService service.
// All implementations must embed UnimplementedStatusServiceServer
// for forward compatibility
type StatusServiceServer interface {
	Get(context.Context, *StatusGetRequest) (*StatusGetResponse, error)
	Watch(*StatusWatchRequest, StatusService_WatchServer) error
	mustEmbedUnimplementedStatusServiceServer()
}

// UnimplementedStatusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatusServiceServer struct {
}

func (UnimplementedStatusServiceServer) Get(context.Context, *StatusGetRequest) (*StatusGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStatusServiceServer) Watch(*StatusWatchRequest, StatusService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedStatusServiceServer) mustEmbedUnimplementedStatusServiceServer() {}

// UnsafeStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusServiceServer will
// result in compilation errors.
type UnsafeStatusServiceServer interface {
	mustEmbedUnimplementedStatusServiceServer()
}

func RegisterStatusServiceServer(s grpc.ServiceRegistrar, srv StatusServiceServer) {
	s.RegisterService(&_StatusService_serviceDesc, srv)
}

func _StatusService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linuxcnc.api.v1.StatusService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).Get(ctx, req.(*StatusGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatusService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatusServiceServer).Watch(m, &statusServiceWatchServer{stream})
}

type StatusService_WatchServer interface {
	Send(*StatusWatchResponse) error
	grpc.ServerStream
}

type statusServiceWatchServer struct {
	grpc.ServerStream
}

func (x *statusServiceWatchServer) Send(m *StatusWatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StatusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "linuxcnc.api.v1.StatusService",
	HandlerType: (*StatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StatusService_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _StatusService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "status.proto",
}
