name: ui
description: A web app that uses AngularDart Components
# version: 0.0.``
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^7.0.0
  angular_router: ^3.0.0
  js: ^0.6.3
  amdjs: ^2.0.1

dev_dependencies:
  sass_builder: ^2.1.2
  angular_test: ^4.0.1
  build_runner: ^2.1.0
  build_test: ^2.1.4
  build_web_compilers: ^3.2.1
  meta: ^1.7.0
  test: ^1.19.5
